changes for firmware version v1.11.0

diff --git a/ROMFS/px4fmu_common/init.d-posix/rcS b/ROMFS/px4fmu_common/init.d-posix/rcS
--- a/ROMFS/px4fmu_common/init.d-posix/rcS
+++ b/ROMFS/px4fmu_common/init.d-posix/rcS
@@ -32,7 +32,8 @@ set PWM_OUT                     none
 set SDCARD_MIXERS_PATH          etc/mixers
 set USE_IO                      no
 set VEHICLE_TYPE                none
-set LOGGER_BUF			1000
+set LOGGER_ARGS                 ""
+set LOGGER_BUF                  1000
 
 set RUN_MINIMAL_SHELL           no
 
@@ -55,9 +56,21 @@ fi
 
 
 uorb start
-if [ -f eeprom/parameters ]
+
+# Load parameters
+set PARAM_FILE eeprom/parameters_"$REQUESTED_AUTOSTART"
+param select $PARAM_FILE
+
+if [ -f $PARAM_FILE ]
 then
-	param load
+	if param load
+	then
+		echo "[param] Loaded: $PARAM_FILE"
+	else
+		echo "[param] FAILED loading $PARAM_FILE"
+	fi
+else
+	echo "[param] parameter file not found, creating $PARAM_FILE"
 fi
 
 # exit early when the minimal shell is requested
@@ -80,11 +93,16 @@ then
 	set AUTOCNF no
 else
 	set AUTOCNF yes
+	param set SYS_AUTOCONFIG 1
 fi
 
-# multi-instance setup
-# shellcheck disable=SC2154
-param set MAV_SYS_ID $((px4_instance))
+if param compare SYS_AUTOCONFIG 1
+then
+	set AUTOCNF yes
+
+	# Wipe out params except RC*, flight modes, total flight time, accel cal, gyro cal, next flight UUID
+	param reset_nostart RC* COM_FLTMODE* LND_FLIGHT_T_* TC_* CAL_ACC* CAL_GYRO* COM_FLIGHT_UUID
+fi
 
 # setting correctly ports
 vehicle_base_port=$((14000 + px4_instance * 4))
@@ -98,62 +116,47 @@ if [ $AUTOCNF = yes ]
 then
 	param set SYS_AUTOSTART $REQUESTED_AUTOSTART
 
-	param set BAT_N_CELLS 3
+	param set BAT_N_CELLS 4
 
 	param set CAL_ACC0_ID 1311244
 	param set CAL_ACC_PRIME 1311244
 
-	param set CAL_GYRO0_ID 2294028
-	param set CAL_GYRO_PRIME 2294028
+	param set CAL_GYRO0_ID 1311244
+	param set CAL_GYRO_PRIME 1311244
 
 	param set CAL_MAG0_ID 197388
 	param set CAL_MAG_PRIME 197388
 
-	param set CAL_BARO_PRIME 6620172
-
 	param set CBRK_AIRSPD_CHK 0
+	param set CBRK_SUPPLY_CHK 894281
 
-	param set COM_DISARM_LAND 0.1
-	param set COM_OBL_ACT 2
-	param set COM_OBL_RC_ACT 0
-	param set COM_OF_LOSS_T 5
+	# Don't require RC calibration and configuration
 	param set COM_RC_IN_MODE 1
 
-	param set EKF2_AID_MASK 1
 	param set EKF2_ANGERR_INIT 0.01
-	param set EKF2_HGT_MODE 0
 	param set EKF2_GBIAS_INIT 0.01
+
+	# Prevent high accel bias
+	param set COM_ARM_EKF_AB 0.005
+
 	# Speedup SITL startup
 	param set EKF2_REQ_GPS_H 0.5
 
 	# LPE: GPS only mode
 	param set LPE_FUSION 145
 
-	param set MIS_TAKEOFF_ALT 2.5
-
 	param set MC_PITCH_P 6
 	param set MC_PITCHRATE_P 0.2
 	param set MC_ROLL_P 6
 	param set MC_ROLLRATE_P 0.2
 
-	param set MPC_ALT_MODE 0
-	param set MPC_HOLD_MAX_Z 2
-	param set MPC_Z_VEL_I 0.15
-	param set MPC_Z_VEL_P 0.6
+	param set MPC_Z_VEL_P_ACC 12.0
+	param set MPC_Z_VEL_I_ACC 3.0
 	param set MPC_XY_P 0.8
-	param set MPC_XY_VEL_P 0.2
-	param set MPC_XY_VEL_I 0.02
-	param set MPC_XY_VEL_D 0.016
+	param set MPC_XY_VEL_P_ACC 4.0
+	param set MPC_XY_VEL_I_ACC 0.4
+	param set MPC_XY_VEL_D_ACC 0.32
 
-	param set MPC_JERK_MIN 10
-	param set MPC_JERK_MAX 20
-	param set MPC_ACC_HOR_MAX 3
-
-	param set NAV_ACC_RAD 2
-	param set NAV_DLL_ACT 2
-
-	param set RTL_DESCEND_ALT 5
-	param set RTL_LAND_DELAY 5
 	param set RTL_RETURN_ALT 30
 
 	# By default log from boot until first disarm.
@@ -167,21 +170,24 @@ then
 	param set SYS_RESTART_TYPE 2
 
 	param set TRIG_INTERFACE 3
-
-	# param set WEST_EN 0
 fi
 
+param set COM_CPU_MAX -1 # disable check, no CPU load reported on posix yet
+
+# Simulator IMU data provided at 250 Hz
+param set IMU_INTEG_RATE 250
+
 # Adapt timeout parameters if simulation runs faster or slower than realtime.
-if [ ! -z $PX4_SIM_SPEED_FACTOR ]; then
+if [ -n "$PX4_SIM_SPEED_FACTOR" ]; then
 	COM_DL_LOSS_T_LONGER=$(echo "$PX4_SIM_SPEED_FACTOR * 10" | bc)
 	echo "COM_DL_LOSS_T set to $COM_DL_LOSS_T_LONGER"
 	param set COM_DL_LOSS_T $COM_DL_LOSS_T_LONGER
 
-	COM_RC_LOSS_T_LONGER=$(echo "$PX4_SIM_SPEED_FACTOR * 1" | bc)
+	COM_RC_LOSS_T_LONGER=$(echo "$PX4_SIM_SPEED_FACTOR * 0.5" | bc)
 	echo "COM_RC_LOSS_T set to $COM_RC_LOSS_T_LONGER"
 	param set COM_RC_LOSS_T $COM_RC_LOSS_T_LONGER
 
-	COM_OF_LOSS_T_LONGER=$(echo "$PX4_SIM_SPEED_FACTOR * 10" | bc)
+	COM_OF_LOSS_T_LONGER=$(echo "$PX4_SIM_SPEED_FACTOR * 0.5" | bc)
 	echo "COM_OF_LOSS_T set to $COM_OF_LOSS_T_LONGER"
 	param set COM_OF_LOSS_T $COM_OF_LOSS_T_LONGER
 fi
@@ -207,23 +213,27 @@ fi
 
 sh "$autostart_file"
 
+#
+# If autoconfig parameter was set, reset it and save parameters.
+#
+if [ $AUTOCNF = yes ]
+then
+	param set SYS_AUTOCONFIG 0
+fi
 
 dataman start
-replay tryapplyparams
-simulator start -c $simulator_tcp_port
+# only start the simulator if not in replay mode, as both control the lockstep time
+if ! replay tryapplyparams
+then
+	simulator start -c $simulator_tcp_port
+fi
+battery_simulator start
 tone_alarm start
-# gyrosim start
-# accelsim start
-# barosim start
-gpssim start
+rc_update start
 sensors start
 commander start
 navigator start
 
-# if param compare WEST_EN 1
-# then
-# 	wind_estimator start
-# fi
 
 if ! param compare -s MNT_MODE_IN -1
 then
@@ -270,6 +280,12 @@ mavlink stream -r 100 -s HEARTBEAT -u $udp_offboard_port_local
 [ -e "$autostart_file".post ] && sh "$autostart_file".post
 
 # Run script to start logging
+if param compare SYS_MC_EST_GROUP 2
+then
+	set LOGGER_ARGS "-p ekf2_timestamps"
+else
+	set LOGGER_ARGS "-p vehicle_attitude"
+fi
 sh etc/init.d/rc.logging
 
 mavlink boot_complete
