spawning many iris does not kill gazebo

diff --git a/ROMFS/px4fmu_common/init.d-posix/rcS b/ROMFS/px4fmu_common/init.d-posix/rcS
--- a/ROMFS/px4fmu_common/init.d-posix/rcS
+++ b/ROMFS/px4fmu_common/init.d-posix/rcS
@@ -6,6 +6,7 @@
 . px4-alias.sh
 
 SCRIPT_DIR="$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)"
+AIRFRAMES_DIR="$SCRIPT_DIR/airframes"
 
 #
 # Main SITL startup script
@@ -15,7 +16,7 @@ SCRIPT_DIR="$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)"
 # shellcheck disable=SC2154
 if [ "$replay_mode" = "ekf2" ]
 then
-	. ${R}etc/init.d-posix/rc.replay
+	sh etc/init.d-posix/rc.replay
 	exit 0
 fi
 
@@ -44,12 +45,10 @@ else
 	# Find the matching Autostart ID (file name has the form: [0-9]+_${PX4_SIM_MODEL})
 	# TODO: unify with rc.autostart generation
 	# shellcheck disable=SC2012
-	REQUESTED_AUTOSTART=$(ls "$SCRIPT_DIR/airframes" | sed -n 's/^\([0-9][0-9]*\)_'${PX4_SIM_MODEL}'$/\1/p')
+	REQUESTED_AUTOSTART=$(ls "$AIRFRAMES_DIR" | sed -n 's/^\([0-9][0-9]*\)_'${PX4_SIM_MODEL}'$/\1/p')
 	if [ -z "$REQUESTED_AUTOSTART" ]; then
-		echo "Error: Unknown model $PX4_SIM_MODEL (not found by name on $SCRIPT_DIR/airframes)"
+		echo "Error: Model '$PX4_SIM_MODEL' not found in '$AIRFRAMES_DIR'"
 		exit 1
-	else
-		echo "Info: found model autostart file as SYS_AUTOSTART=$REQUESTED_AUTOSTART"
 	fi
 fi
 
@@ -103,20 +102,19 @@ then
 	set AUTOCNF yes
 
 	# Wipe out params except RC*, flight modes, total flight time, accel cal, gyro cal, next flight UUID
-	param reset_all SYS_AUTOSTART SYS_AUTOCONFIG RC* COM_FLTMODE* LND_FLIGHT_T_* TC_* CAL_ACC* CAL_GYRO* COM_FLIGHT_UUID
+	param reset_nostart RC* COM_FLTMODE* LND_FLIGHT_T_* TC_* CAL_ACC* CAL_GYRO* COM_FLIGHT_UUID
 fi
 
 # multi-instance setup
 # shellcheck disable=SC2154
-# setting MAV_ID
-param set MAV_SYS_ID $((px4_instance))
-
-# setting correctly ports
-vehicle_base_port=$((14000 + px4_instance * 4))
-simulator_tcp_port=$((4560 + px4_instance))
-udp_gcs_port_local=$((vehicle_base_port + 1))
-udp_offboard_port_local=$((vehicle_base_port + 2))
-udp_offboard_port_remote=$((vehicle_base_port + 3))
+param set MAV_SYS_ID $((px4_instance+1))
+simulator_tcp_port=$((4560+px4_instance))
+udp_offboard_port_local=$((14580+px4_instance))
+udp_offboard_port_remote=$((14540+px4_instance))
+[ $px4_instance -gt 9 ] && udp_offboard_port_remote=14549 # use the same ports for more than 10 instances to avoid port overlaps
+udp_onboard_payload_port_local=$((14280+px4_instance))
+udp_onboard_payload_port_remote=$((14030+px4_instance))
+udp_gcs_port_local=$((18570+px4_instance))
 
 if [ $AUTOCNF = yes ]
 then
@@ -124,14 +122,14 @@ then
 
 	param set BAT_N_CELLS 4
 
-	param set CAL_ACC0_ID 1310988 # 1310988: DRV_IMU_DEVTYPE_SIM, BUS: 1, ADDR: 1, TYPE: SIMULATION
-	param set CAL_ACC1_ID 1310996 # 1310996: DRV_IMU_DEVTYPE_SIM, BUS: 2, ADDR: 1, TYPE: SIMULATION
-	param set CAL_ACC2_ID 1311004 # 1311004: DRV_IMU_DEVTYPE_SIM, BUS: 3, ADDR: 1, TYPE: SIMULATION
-	param set CAL_GYRO0_ID 1310988 # 1310988: DRV_IMU_DEVTYPE_SIM, BUS: 1, ADDR: 1, TYPE: SIMULATION
-	param set CAL_GYRO1_ID 1310996 # 1310996: DRV_IMU_DEVTYPE_SIM, BUS: 2, ADDR: 1, TYPE: SIMULATION
-	param set CAL_GYRO2_ID 1311004 # 1311004: DRV_IMU_DEVTYPE_SIM, BUS: 3, ADDR: 1, TYPE: SIMULATION
+	param set CAL_ACC0_ID 1311244
+	param set CAL_ACC_PRIME 1311244
+
+	param set CAL_GYRO0_ID 1311244
+	param set CAL_GYRO_PRIME 1311244
+
 	param set CAL_MAG0_ID 197388
-	param set CAL_MAG1_ID 197644
+	param set CAL_MAG_PRIME 197388
 
 	param set CBRK_AIRSPD_CHK 0
 	param set CBRK_SUPPLY_CHK 894281
@@ -139,14 +137,31 @@ then
 	# Don't require RC calibration and configuration
 	param set COM_RC_IN_MODE 1
 
-  # Speedup SITL startup
+	param set EKF2_ANGERR_INIT 0.01
+	param set EKF2_GBIAS_INIT 0.01
+
+	# Prevent high accel bias
+	param set COM_ARM_EKF_AB 0.005
+
+	# Speedup SITL startup
 	param set EKF2_REQ_GPS_H 0.5
 
-	# Multi-EKF
-	param set EKF2_MULTI_IMU 3
-	param set SENS_IMU_MODE 0
-	param set EKF2_MULTI_MAG 2
-	param set SENS_MAG_MODE 0
+	# LPE: GPS only mode
+	param set LPE_FUSION 145
+
+	param set MC_PITCH_P 6
+	param set MC_PITCHRATE_P 0.2
+	param set MC_ROLL_P 6
+	param set MC_ROLLRATE_P 0.2
+
+	param set MPC_Z_VEL_P_ACC 12.0
+	param set MPC_Z_VEL_I_ACC 3.0
+	param set MPC_XY_P 0.8
+	param set MPC_XY_VEL_P_ACC 4.0
+	param set MPC_XY_VEL_I_ACC 0.4
+	param set MPC_XY_VEL_D_ACC 0.32
+
+	param set RTL_RETURN_ALT 30
 
 	# By default log from boot until first disarm.
 	param set SDLOG_MODE 1
@@ -183,8 +198,7 @@ fi
 
 # Autostart ID
 autostart_file=''
-# shellcheck disable=SC2231
-for f in ${R}etc/init.d-posix/airframes/"$(param show -q SYS_AUTOSTART)"_*
+for f in etc/init.d-posix/airframes/"$(param show -q SYS_AUTOSTART)"_*
 do
 	filename=$(basename "$f")
 	case "$filename" in
@@ -201,7 +215,7 @@ if [ ! -e "$autostart_file" ]; then
 	exit 1
 fi
 
-. "$autostart_file"
+sh "$autostart_file"
 
 #
 # If autoconfig parameter was set, reset it and save parameters.
@@ -217,7 +231,6 @@ if ! replay tryapplyparams
 then
 	simulator start -c $simulator_tcp_port
 fi
-load_mon start
 battery_simulator start
 tone_alarm start
 rc_update start
@@ -226,7 +239,7 @@ commander start
 navigator start
 
 
-if param greater -s MNT_MODE_IN -1
+if ! param compare -s MNT_MODE_IN -1
 then
 	vmount start
 fi
@@ -241,34 +254,28 @@ fi
 # Note: rc.vehicle_setup is the entry point for rc.interface,
 #       rc.fw_apps, rc.mc_apps, rc.rover_apps, and rc.vtol_apps.
 #
-. ${R}etc/init.d/rc.vehicle_setup
+sh etc/init.d/rc.vehicle_setup
 
 # GCS link
 mavlink start -x -u $udp_gcs_port_local -r 4000000
-# mavlink stream -r 50 -s POSITION_TARGET_LOCAL_NED -u $udp_gcs_port_local
-# mavlink stream -r 50 -s LOCAL_POSITION_NED -u $udp_gcs_port_local
-# mavlink stream -r 50 -s GLOBAL_POSITION_INT -u $udp_gcs_port_local
-# mavlink stream -r 50 -s ATTITUDE -u $udp_gcs_port_local
-# mavlink stream -r 50 -s ATTITUDE_QUATERNION -u $udp_gcs_port_local
-# mavlink stream -r 50 -s ATTITUDE_TARGET -u $udp_gcs_port_local
-# mavlink stream -r 50 -s SERVO_OUTPUT_RAW_0 -u $udp_gcs_port_local
-# mavlink stream -r 20 -s RC_CHANNELS -u $udp_gcs_port_local
-# mavlink stream -r 10 -s OPTICAL_FLOW_RAD -u $udp_gcs_port_local
+mavlink stream -r 50 -s POSITION_TARGET_LOCAL_NED -u $udp_gcs_port_local
+mavlink stream -r 50 -s LOCAL_POSITION_NED -u $udp_gcs_port_local
+mavlink stream -r 50 -s GLOBAL_POSITION_INT -u $udp_gcs_port_local
+mavlink stream -r 50 -s ATTITUDE -u $udp_gcs_port_local
+mavlink stream -r 50 -s ATTITUDE_QUATERNION -u $udp_gcs_port_local
+mavlink stream -r 50 -s ATTITUDE_TARGET -u $udp_gcs_port_local
+mavlink stream -r 50 -s SERVO_OUTPUT_RAW_0 -u $udp_gcs_port_local
+mavlink stream -r 20 -s RC_CHANNELS -u $udp_gcs_port_local
+mavlink stream -r 10 -s OPTICAL_FLOW_RAD -u $udp_gcs_port_local
 
 # API/Offboard link
 mavlink start -x -u $udp_offboard_port_local -r 4000000 -m onboard -o $udp_offboard_port_remote
-mavlink stream -r 100 -s ATTITUDE -u $udp_offboard_port_local
-mavlink stream -r 100 -s ATTITUDE_QUATERNION -u $udp_offboard_port_local # /mavros/imu/data
-mavlink stream -r 100 -s ATTITUDE_TARGET -u $udp_offboard_port_local
-mavlink stream -r 100 -s HIGHRES_IMU -u $udp_offboard_port_local # /mavros/imu/data_raw
-mavlink stream -r 10  -s RC_CHANNELS -u $udp_offboard_port_local
-mavlink stream -r 100 -s LOCAL_POSITION_NED -u $udp_offboard_port_local
-mavlink stream -r 100 -s GLOBAL_POSITION_INT -u $udp_offboard_port_local
-mavlink stream -r 10  -s SYS_STATUS -u $udp_offboard_port_local
-mavlink stream -r 100 -s HEARTBEAT -u $udp_offboard_port_local
+
+# Onboard link to camera
+mavlink start -x -u $udp_onboard_payload_port_local -r 4000 -f -m onboard -o $udp_onboard_payload_port_remote
 
 # execute autostart post script if any
-[ -e "$autostart_file".post ] && . "$autostart_file".post
+[ -e "$autostart_file".post ] && sh "$autostart_file".post
 
 # Run script to start logging
 if param compare SYS_MC_EST_GROUP 2
@@ -277,7 +284,7 @@ then
 else
 	set LOGGER_ARGS "-p vehicle_attitude"
 fi
-. ${R}etc/init.d/rc.logging
+sh etc/init.d/rc.logging
 
 mavlink boot_complete
 replay trystart
