revert back to old version of firmware (v1.10.1)

diff --git a/ROMFS/px4fmu_common/init.d-posix/rcS b/ROMFS/px4fmu_common/init.d-posix/rcS
--- a/ROMFS/px4fmu_common/init.d-posix/rcS
+++ b/ROMFS/px4fmu_common/init.d-posix/rcS
@@ -15,7 +15,7 @@ SCRIPT_DIR="$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)"
 # shellcheck disable=SC2154
 if [ "$replay_mode" = "ekf2" ]
 then
-	. ${R}etc/init.d-posix/rc.replay
+	sh etc/init.d-posix/rc.replay
 	exit 0
 fi
 
@@ -32,8 +32,7 @@ set PWM_OUT                     none
 set SDCARD_MIXERS_PATH          etc/mixers
 set USE_IO                      no
 set VEHICLE_TYPE                none
-set LOGGER_ARGS                 ""
-set LOGGER_BUF                  1000
+set LOGGER_BUF			1000
 
 set RUN_MINIMAL_SHELL           no
 
@@ -44,12 +43,10 @@ else
 	# Find the matching Autostart ID (file name has the form: [0-9]+_${PX4_SIM_MODEL})
 	# TODO: unify with rc.autostart generation
 	# shellcheck disable=SC2012
-	REQUESTED_AUTOSTART=$(ls "$SCRIPT_DIR/airframes" | sed -n 's/^\([0-9][0-9]*\)_'${PX4_SIM_MODEL}'$/\1/p')
+	REQUESTED_AUTOSTART=$(ls "$SCRIPT_DIR" | sed -n 's/^\([0-9][0-9]*\)_'${PX4_SIM_MODEL}'$/\1/p')
 	if [ -z "$REQUESTED_AUTOSTART" ]; then
-		echo "Error: Unknown model $PX4_SIM_MODEL (not found by name on $SCRIPT_DIR/airframes)"
+		echo "Error: Unknown model '$PX4_SIM_MODEL'"
 		exit 1
-	else
-		echo "Info: found model autostart file as SYS_AUTOSTART=$REQUESTED_AUTOSTART"
 	fi
 fi
 
@@ -58,21 +55,9 @@ fi
 
 
 uorb start
-
-# Load parameters
-set PARAM_FILE eeprom/parameters_"$REQUESTED_AUTOSTART"
-param select $PARAM_FILE
-
-if [ -f $PARAM_FILE ]
+if [ -f eeprom/parameters ]
 then
-	if param load
-	then
-		echo "[param] Loaded: $PARAM_FILE"
-	else
-		echo "[param] FAILED loading $PARAM_FILE"
-	fi
-else
-	echo "[param] parameter file not found, creating $PARAM_FILE"
+	param load
 fi
 
 # exit early when the minimal shell is requested
@@ -95,24 +80,15 @@ then
 	set AUTOCNF no
 else
 	set AUTOCNF yes
-	param set SYS_AUTOCONFIG 1
-fi
-
-if param compare SYS_AUTOCONFIG 1
-then
-	set AUTOCNF yes
-
-	# Wipe out params except RC*, flight modes, total flight time, accel cal, gyro cal, next flight UUID
-	param reset_all SYS_AUTOSTART SYS_AUTOCONFIG RC* COM_FLTMODE* LND_FLIGHT_T_* TC_* CAL_ACC* CAL_GYRO* COM_FLIGHT_UUID
 fi
 
 # multi-instance setup
 # shellcheck disable=SC2154
-# setting MAV_ID
 param set MAV_SYS_ID $((px4_instance))
 
 # setting correctly ports
 vehicle_base_port=$((14000 + px4_instance * 4))
+
 simulator_tcp_port=$((4560 + px4_instance))
 udp_gcs_port_local=$((vehicle_base_port + 1))
 udp_offboard_port_local=$((vehicle_base_port + 2))
@@ -122,31 +98,63 @@ if [ $AUTOCNF = yes ]
 then
 	param set SYS_AUTOSTART $REQUESTED_AUTOSTART
 
-	param set BAT_N_CELLS 4
+	param set BAT_N_CELLS 3
 
-	param set CAL_ACC0_ID 1310988 # 1310988: DRV_IMU_DEVTYPE_SIM, BUS: 1, ADDR: 1, TYPE: SIMULATION
-	param set CAL_ACC1_ID 1310996 # 1310996: DRV_IMU_DEVTYPE_SIM, BUS: 2, ADDR: 1, TYPE: SIMULATION
-	param set CAL_ACC2_ID 1311004 # 1311004: DRV_IMU_DEVTYPE_SIM, BUS: 3, ADDR: 1, TYPE: SIMULATION
-	param set CAL_GYRO0_ID 1310988 # 1310988: DRV_IMU_DEVTYPE_SIM, BUS: 1, ADDR: 1, TYPE: SIMULATION
-	param set CAL_GYRO1_ID 1310996 # 1310996: DRV_IMU_DEVTYPE_SIM, BUS: 2, ADDR: 1, TYPE: SIMULATION
-	param set CAL_GYRO2_ID 1311004 # 1311004: DRV_IMU_DEVTYPE_SIM, BUS: 3, ADDR: 1, TYPE: SIMULATION
+	param set CAL_ACC0_ID 1311244
+	param set CAL_ACC_PRIME 1311244
+
+	param set CAL_GYRO0_ID 2294028
+	param set CAL_GYRO_PRIME 2294028
+
 	param set CAL_MAG0_ID 197388
-	param set CAL_MAG1_ID 197644
+	param set CAL_MAG_PRIME 197388
+
+	param set CAL_BARO_PRIME 6620172
 
 	param set CBRK_AIRSPD_CHK 0
-	param set CBRK_SUPPLY_CHK 894281
 
-	# Don't require RC calibration and configuration
+	param set COM_DISARM_LAND 0.1
+	param set COM_OBL_ACT 2
+	param set COM_OBL_RC_ACT 0
+	param set COM_OF_LOSS_T 5
 	param set COM_RC_IN_MODE 1
 
-  # Speedup SITL startup
+	param set EKF2_AID_MASK 1
+	param set EKF2_ANGERR_INIT 0.01
+	param set EKF2_HGT_MODE 0
+	param set EKF2_GBIAS_INIT 0.01
+	# Speedup SITL startup
 	param set EKF2_REQ_GPS_H 0.5
 
-	# Multi-EKF
-	param set EKF2_MULTI_IMU 3
-	param set SENS_IMU_MODE 0
-	param set EKF2_MULTI_MAG 2
-	param set SENS_MAG_MODE 0
+	# LPE: GPS only mode
+	param set LPE_FUSION 145
+
+	param set MIS_TAKEOFF_ALT 2.5
+
+	param set MC_PITCH_P 6
+	param set MC_PITCHRATE_P 0.2
+	param set MC_ROLL_P 6
+	param set MC_ROLLRATE_P 0.2
+
+	param set MPC_ALT_MODE 0
+	param set MPC_HOLD_MAX_Z 2
+	param set MPC_Z_VEL_I 0.15
+	param set MPC_Z_VEL_P 0.6
+	param set MPC_XY_P 0.8
+	param set MPC_XY_VEL_P 0.2
+	param set MPC_XY_VEL_I 0.02
+	param set MPC_XY_VEL_D 0.016
+
+	param set MPC_JERK_MIN 10
+	param set MPC_JERK_MAX 20
+	param set MPC_ACC_HOR_MAX 3
+
+	param set NAV_ACC_RAD 2
+	param set NAV_DLL_ACT 2
+
+	param set RTL_DESCEND_ALT 5
+	param set RTL_LAND_DELAY 5
+	param set RTL_RETURN_ALT 30
 
 	# By default log from boot until first disarm.
 	param set SDLOG_MODE 1
@@ -159,32 +167,28 @@ then
 	param set SYS_RESTART_TYPE 2
 
 	param set TRIG_INTERFACE 3
+
+	# param set WEST_EN 0
 fi
 
-param set COM_CPU_MAX -1 # disable check, no CPU load reported on posix yet
-
-# Simulator IMU data provided at 250 Hz
-param set IMU_INTEG_RATE 250
-
 # Adapt timeout parameters if simulation runs faster or slower than realtime.
-if [ -n "$PX4_SIM_SPEED_FACTOR" ]; then
+if [ ! -z $PX4_SIM_SPEED_FACTOR ]; then
 	COM_DL_LOSS_T_LONGER=$(echo "$PX4_SIM_SPEED_FACTOR * 10" | bc)
 	echo "COM_DL_LOSS_T set to $COM_DL_LOSS_T_LONGER"
 	param set COM_DL_LOSS_T $COM_DL_LOSS_T_LONGER
 
-	COM_RC_LOSS_T_LONGER=$(echo "$PX4_SIM_SPEED_FACTOR * 0.5" | bc)
+	COM_RC_LOSS_T_LONGER=$(echo "$PX4_SIM_SPEED_FACTOR * 1" | bc)
 	echo "COM_RC_LOSS_T set to $COM_RC_LOSS_T_LONGER"
 	param set COM_RC_LOSS_T $COM_RC_LOSS_T_LONGER
 
-	COM_OF_LOSS_T_LONGER=$(echo "$PX4_SIM_SPEED_FACTOR * 0.5" | bc)
+	COM_OF_LOSS_T_LONGER=$(echo "$PX4_SIM_SPEED_FACTOR * 10" | bc)
 	echo "COM_OF_LOSS_T set to $COM_OF_LOSS_T_LONGER"
 	param set COM_OF_LOSS_T $COM_OF_LOSS_T_LONGER
 fi
 
 # Autostart ID
 autostart_file=''
-# shellcheck disable=SC2231
-for f in ${R}etc/init.d-posix/airframes/"$(param show -q SYS_AUTOSTART)"_*
+for f in etc/init.d-posix/"$(param show -q SYS_AUTOSTART)"_*
 do
 	filename=$(basename "$f")
 	case "$filename" in
@@ -201,32 +205,27 @@ if [ ! -e "$autostart_file" ]; then
 	exit 1
 fi
 
-. "$autostart_file"
+sh "$autostart_file"
 
-#
-# If autoconfig parameter was set, reset it and save parameters.
-#
-if [ $AUTOCNF = yes ]
-then
-	param set SYS_AUTOCONFIG 0
-fi
 
 dataman start
-# only start the simulator if not in replay mode, as both control the lockstep time
-if ! replay tryapplyparams
-then
-	simulator start -c $simulator_tcp_port
-fi
-load_mon start
-battery_simulator start
+replay tryapplyparams
+simulator start -c $simulator_tcp_port
 tone_alarm start
-rc_update start
+# gyrosim start
+# accelsim start
+# barosim start
+gpssim start
 sensors start
 commander start
 navigator start
 
+# if param compare WEST_EN 1
+# then
+# 	wind_estimator start
+# fi
 
-if param greater -s MNT_MODE_IN -1
+if ! param compare -s MNT_MODE_IN -1
 then
 	vmount start
 fi
@@ -241,7 +240,7 @@ fi
 # Note: rc.vehicle_setup is the entry point for rc.interface,
 #       rc.fw_apps, rc.mc_apps, rc.rover_apps, and rc.vtol_apps.
 #
-. ${R}etc/init.d/rc.vehicle_setup
+sh etc/init.d/rc.vehicle_setup
 
 # GCS link
 mavlink start -x -u $udp_gcs_port_local -r 4000000
@@ -268,16 +267,10 @@ mavlink stream -r 10  -s SYS_STATUS -u $udp_offboard_port_local
 mavlink stream -r 100 -s HEARTBEAT -u $udp_offboard_port_local
 
 # execute autostart post script if any
-[ -e "$autostart_file".post ] && . "$autostart_file".post
+[ -e "$autostart_file".post ] && sh "$autostart_file".post
 
 # Run script to start logging
-if param compare SYS_MC_EST_GROUP 2
-then
-	set LOGGER_ARGS "-p ekf2_timestamps"
-else
-	set LOGGER_ARGS "-p vehicle_attitude"
-fi
-. ${R}etc/init.d/rc.logging
+sh etc/init.d/rc.logging
 
 mavlink boot_complete
 replay trystart
